import {test} from 'node:test';
import assert from 'node:assert/strict';
import {jobEmail,deliverJobEmail} from '../supabase/functions/mowmatter-crew/email.mjs';
function setup(overrides={}){
 const rows={mow_crew_notifications:{id:'notification',event_id:'event',company_id:'company',job_id:'job',channel:'sms',status:'pending_provider',created_at:new Date().toISOString()},mow_crew_jobs:{id:'job',company_id:'company',notification_consent:true,customer_email:'test@example.invalid',address:'1 Test Lane',service_date:'2026-10-06'},mow_crew_events:{action:'start'},mow_crew_companies:{name:'Test Crew'}};
 for(const [table,patch] of Object.entries(overrides))Object.assign(rows[table],patch);
 const sends=[];const db={from(table){let changes,filters=[];const q={select(){return q},eq(k,v){filters.push([k,v]);return q},update(v){changes=v;return q},maybeSingle(){return q},single(){return q},then(resolve){let row=rows[table];if(filters.some(([k,v])=>row[k]!==undefined&&row[k]!==v))row=null;if(row&&changes)Object.assign(row,changes);resolve({data:row,error:null})}};return q}};
 const send=async(url,opts)=>{sends.push({url,...opts});return {ok:true,json:async()=>({id:'provider-id'})}};
 return {db,rows,sends,send};
}
test('escapes customer and business data',()=>{const m=jobEmail('<script>',{address:'<img>',service_date:'2026-10-06'},'complete');assert(!m.html.includes('<script>'));assert(!m.html.includes('<img>'));assert(m.html.includes('&lt;img&gt;'));assert(m.subject.startsWith('All handled'))});
test('missing key, consent, contact, cancelled or historical job never sends',async()=>{for(const override of [{mow_crew_jobs:{notification_consent:false}},{mow_crew_jobs:{customer_email:''}},{mow_crew_jobs:{cancelled_at:'now'}},{mow_crew_notifications:{created_at:'2020-01-01'}},{mow_crew_notifications:{status:'sent'}}]){const x=setup(override);await deliverJobEmail(x.db,'company','event','test-key',x.send);assert.equal(x.sends.length,0)}const x=setup();await deliverJobEmail(x.db,'company','event',undefined,x.send);assert.equal(x.sends.length,0)});
test('company scope, stable idempotency, email-only delivery, sent suppression',async()=>{const x=setup();assert.equal(await deliverJobEmail(x.db,'other-company','event','test-key',x.send),null);assert.equal(await deliverJobEmail(x.db,'company','event','test-key',x.send),'sent');assert.equal(x.sends.length,1);assert.equal(x.sends[0].headers['Idempotency-Key'],'mowmatter-job-event');assert.deepEqual(JSON.parse(x.sends[0].body).to,['test@example.invalid']);assert.equal(x.rows.mow_crew_notifications.channel,'email');await deliverJobEmail(x.db,'company','event','test-key',x.send);assert.equal(x.sends.length,1)});
test('provider failure is durable and retry retains identifier',async()=>{const x=setup();assert.equal(await deliverJobEmail(x.db,'company','event','test-key',async()=>{throw Error('timeout')}),'failed');assert.equal(x.rows.mow_crew_notifications.status,'failed');assert.equal(await deliverJobEmail(x.db,'company','event','test-key',x.send),'sent');assert.equal(x.sends[0].headers['Idempotency-Key'],'mowmatter-job-event')});
