const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');const path=require('path');const root=path.join(__dirname,'dist');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function idb(seed={}){const stores={queue:new Map(),photos:new Map(),snapshots:new Map()};for(const [n,rows]of Object.entries(seed))rows.forEach(x=>stores[n].set(x.id,x));return {stores,open(){const r={result:{createObjectStore(n){stores[n]??=new Map()},transaction(n){const t={objectStore(){return new Proxy({}, {get(_,op){return v=>{const q={};setTimeout(()=>{const s=stores[n];q.result=op==='getAll'?[...s.values()]:op==='get'?s.get(v):op==='put'?(s.set(v.id,v),v.id):s.delete(v);q.onsuccess?.();setTimeout(()=>t.oncomplete?.(),0)},0);return q}}})}};return t}}};setTimeout(()=>{r.onupgradeneeded?.();r.onsuccess?.()},0);return r}}}
const today=()=>new Date().toISOString().slice(0,10);
const job=(id,status='scheduled')=>({id,assigned_to:'crew',customer_name:'Test customer',address:id+' Test Lane',city:'Palm Coast, FL',service_date:today(),scheduled_time:'09:00',status,services:['Mow'],requires_photo:false,latitude:29.584,longitude:-81.207});
const snapshot=jobs=>({company:{name:'QA'},profile:{id:'crew',name:'QA Crew',role:'member'},members:[],jobs,events:[],photos:[],messages:[],notifications:[]});
const event=(id,jid,verb)=>({id,event_id:id,user_id:'crew',job_id:jid,verb,details:{},created_at:'2026-10-05T12:00:0'+id.slice(-1)+'Z'});
async function page(view,{demo=false,seed={},api,geo}={}){const d=new JSDOM(fs.readFileSync(path.join(root,view+'.html'),'utf8'),{url:'https://crew.mowmatter.com/'+view+'.html',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.localStorage.setItem('mm-crew-mode',demo?'demo':'live');for(const p of seed.photos||[])p.blob=new w.Blob(['proof'],{type:'image/jpeg'});const db=idb(seed);w.indexedDB=db;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.URL.createObjectURL=()=> 'blob:proof';if(geo)Object.defineProperty(w.navigator,'geolocation',{value:geo});w.MM={ready:Promise.resolve(),session:{user:{id:'crew',email:'qa@example.invalid'}},api:api||(async()=>snapshot([job('one')])),signOut:async()=>{w.MM.session=null}};w.eval(fs.readFileSync(path.join(root,'crew.js'),'utf8'));await wait(130);return {d,w,db,$:s=>w.document.querySelector(s)}}
(async()=>{
 for(const view of ['index','route','jobs','messages','more','job']){const {d,$}=await page(view,{demo:true});assert(!$('.loading'));assert(!$('#main').textContent.includes('storage is unavailable'));d.window.close()}
 const calls=[],jobs=[job('bad'),job('good')];const a=await page('more',{seed:{queue:[event('q1','bad','start'),event('q2','bad','complete'),event('q3','good','start')],photos:[{id:'photo',job_id:'bad',user_id:'crew',blob:new Blob(['proof']),uploaded:false}]},api:async body=>{if(body.action==='list')return snapshot(jobs);if(typeof body.get==='function')throw Error('Upload rejected: job cancelled');calls.push(body);return {ok:true}}});
 // The upload fails before this job's start; another job must still sync.
 assert.equal(a.db.stores.queue.size,2);assert(calls.some(x=>x.job_id==='good'));assert(!calls.some(x=>x.job_id==='bad'));assert(a.db.stores.queue.get('q1').error.includes('Upload rejected'));assert(a.$('#connection').textContent.includes('Needs attention'));
 a.$('#connection').click();a.$('[data-review-job]').click();assert(a.$('#dialog-content').textContent.includes('2 local job updates and 1 photo'));assert.equal(a.db.stores.queue.size,2);a.$('#keep-updates').click();assert.equal(a.db.stores.queue.size,2);a.$('[data-review-job]').click();a.$('#discard-updates').click();await wait(100);assert.equal(a.db.stores.queue.size,0);assert.equal(a.db.stores.photos.size,0);assert.equal(jobs[0].status,'scheduled');a.d.window.close();
 let position,error,cleared;const g=await page('index',{geo:{watchPosition(ok,fail){position=ok;error=fail;return 9},clearWatch(id){cleared=id}}});g.$('[data-action="gps"]').click();position({coords:{latitude:29.584,longitude:-81.207,accuracy:20},timestamp:Date.now()});assert(g.$('#dialog-content').textContent.includes('Ready to check in'));assert(!g.$('#dialog-content').textContent.includes('Job started'));g.$('#close-dialog').click();error();assert.equal(cleared,9);g.d.window.close();
 const bCalls=[],b=await page('more',{seed:{queue:[event('q1','bad','start'),event('q2','bad','complete'),event('q3','good','start')]},api:async body=>{if(body.action==='list')return snapshot(jobs);bCalls.push(body);if(body.job_id==='bad')throw Error('Job cancelled');return {ok:true}}});assert.equal(b.db.stores.queue.size,2);assert.equal(bCalls.filter(x=>x.job_id==='bad').length,1);assert(bCalls.some(x=>x.job_id==='good'));b.d.window.close();
 console.log('PASS: six views; photo-failure and transition-failure isolation; same-job ordering; explicit local discard/cancel; GPS confirmation prompt and watcher cleanup');
})().catch(e=>{console.error(e);process.exit(1)});
