import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import Stripe from 'stripe';import {createBilling,subscriptionState,PLANS} from './billing.mjs';
const subscription={status:'active',items:{data:[{price:{id:PLANS.growth.price},current_period_end:2000000000}]},latest_invoice:{status:'paid'}};
test('Only recognized, paid, active subscriptions grant paid state',()=>{assert.equal(subscriptionState(subscription).paid,true);for(const status of ['open','uncollectible','void'])assert.equal(subscriptionState({...subscription,latest_invoice:{status}}).paid,false);assert.equal(subscriptionState({...subscription,status:'past_due'}).paid,false);assert.equal(subscriptionState({...subscription,items:{data:[{price:{id:'unknown'}}]}}).paid,false)});
async function call(handle,path,opts={}){const server=http.createServer((req,res)=>handle(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+server.address().port+path,opts);return {status:r.status,body:await r.json()}}finally{await new Promise(r=>server.close(r))}}
const origin='https://office.mowmatter.com';
test('Missing webhook blocks checkout and configuration never exposes secrets',async()=>{const handle=createBilling({env:{stripe_live_secret_key:'sk_live_TEST_ONLY',supabase_api_secret_key:'fake'},stripeClient:{},fetcher:async()=>new Response('[]')});const r=await call(handle,'/api/billing/config',{headers:{Origin:origin}});assert.equal(r.body.checkout_enabled,false);assert.equal(r.body.webhook_configured,false);assert(!JSON.stringify(r.body).includes('TEST_ONLY'))});
test('Disallowed origins rejected before authentication',async()=>{let requested=false;const h=createBilling({env:{},fetcher:()=>{requested=true;throw Error()}});const r=await call(h,'/api/billing/checkout',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'});assert.equal(r.status,403);assert.equal(requested,false)});
test('Authentication and owner authorization required',async()=>{const h=createBilling({env:{supabase_api_secret_key:'fake'},fetcher:async url=>new Response(JSON.stringify(url.includes('/auth/')?{id:'user1'}:[{role:'crew',company_id:'company1'}]),{status:200})});let r=await call(h,'/api/billing/status',{method:'POST',headers:{Origin:origin},body:'{}'});assert.equal(r.status,401);r=await call(h,'/api/billing/status',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake'},body:'{}'});assert.equal(r.status,403)});
test('Forged webhook rejected without database access',async()=>{const stripe=new Stripe('sk_test_unit_only');let called=false;const h=createBilling({env:{STRIPE_WEBHOOK_SECRET:'whsec_unit_only',supabase_api_secret_key:'fake'},stripeClient:stripe,fetcher:()=>{called=true;throw Error()}});const r=await call(h,'/api/billing/webhook',{method:'POST',headers:{'stripe-signature':'t=1,v1=invalid'},body:'{}'});assert.equal(r.status,400);assert.equal(called,false)});
test('Wrong environment signed webhook rejected',async()=>{const stripe=new Stripe('sk_test_unit_only'),secret='whsec_unit_only',body=JSON.stringify({id:'evt_test',livemode:false,type:'invoice.paid',data:{object:{}}}),sig=stripe.webhooks.generateTestHeaderString({payload:body,secret});const h=createBilling({env:{STRIPE_WEBHOOK_SECRET:secret,supabase_api_secret_key:'fake'},stripeClient:stripe});const r=await call(h,'/api/billing/webhook',{method:'POST',headers:{'stripe-signature':sig},body});assert.equal(r.status,400)});
test('Correct signed lifecycle event syncs known customer through atomic RPC',async()=>{const stripe=new Stripe('sk_test_unit_only'),secret='whsec_unit_only',event={id:'evt_unit',created:12345,livemode:true,type:'invoice.paid',data:{object:{object:'invoice',parent:{subscription_details:{subscription:'sub_unit'}}}}},body=JSON.stringify(event),sig=stripe.webhooks.generateTestHeaderString({payload:body,secret});stripe.subscriptions.retrieve=async id=>({...subscription,id,customer:'cus_unit'});let applied;const h=createBilling({env:{STRIPE_WEBHOOK_SECRET:secret,supabase_api_secret_key:'fake'},stripeClient:stripe,fetcher:async(url,opts)=>{if(url.includes('/rpc/')){applied=JSON.parse(opts.body);return new Response('true')}return new Response(JSON.stringify([{company_id:'company1'}]))}});const r=await call(h,'/api/billing/webhook',{method:'POST',headers:{'stripe-signature':sig},body});assert.equal(r.status,200);assert.equal(applied.customer,'cus_unit');assert.equal(applied.is_paid,true);assert.equal(applied.eid,'evt_unit')});
test('Plan fees use confirmed tiers, round cents, and fall back on unpaid plans',async()=>{const {feePlan,feeCents,FEE_BPS}=await import('./billing.mjs');assert.deepEqual(FEE_BPS,{starter:350,growth:250,scale:150});assert.equal(feeCents(20000,'starter'),700);assert.equal(feeCents(20000,'growth'),500);assert.equal(feeCents(20000,'scale'),300);assert.equal(feeCents(4999,'scale'),75);assert.equal(feePlan({plan:'scale',paid:false,status:'past_due'}),'starter');assert.equal(feePlan({plan:'growth',paid:true,status:'active'}),'growth');assert.throws(()=>feeCents(-100,'scale'))});
test('Completed visit checkout uses stored price and paid-plan fee, never client supplied amounts',async()=>{let input,options;const a={company_id:'company1',customer_id:'acct_operator',plan:'growth',paid:true,status:'active'};const client={accounts:{retrieve:async()=>({id:'acct_1UNcR11fvEozmSlD',charges_enabled:true})},v2:{core:{accounts:{retrieve:async()=>({id:'acct_operator',configuration:{merchant:{capabilities:{card_payments:{status:'active'},stripe_balance:{payouts:{status:'active'}}}}}})}}},checkout:{sessions:{create:async(p,o)=>{input=p;options=o;return {id:'cs_unit',url:'https://checkout.stripe.com/test'}}}}};const h=createBilling({env:{STRIPE_WEBHOOK_SECRET:'whsec_unit',STRIPE_CONNECT_WEBHOOK_SECRET:'whsec_connect_unit',STRIPE_CONNECT_ENABLED:'true',supabase_api_secret_key:'fake'},stripeClient:client,fetcher:async(url,o)=>new Response(JSON.stringify(url.includes('/auth/')?{id:'user1'}:url.includes('mow_crew_members')?[{role:'owner',company_id:'company1'}]:url.includes('mow_crew_jobs')?[{id:'job1',status:'completed',price_cents:20000}]:url.includes('/rpc/')?true:url.includes('mow_payment_checkouts')?[]:[a]))});const r=await call(h,'/api/billing/payment-link',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake'},body:JSON.stringify({company_id:'company1',job_id:'job1',amount:1,fee:0,plan:'scale'})});assert.equal(r.status,200);assert.equal(input.line_items[0].price_data.unit_amount,20000);assert.equal(input.payment_intent_data.application_fee_amount,500);assert.equal(input.payment_intent_data.metadata.fee_bps,'250');assert.equal(options.stripeAccount,'acct_operator');assert.equal(input.mode,'payment')});
test('Connect onboarding never creates account before activation',async()=>{let made=false;const client={accounts:{retrieve:async()=>({id:'acct_1UNcR11fvEozmSlD',charges_enabled:true})},v2:{core:{accounts:{create:async()=>{made=true}}}}};const h=createBilling({env:{supabase_api_secret_key:'fake'},stripeClient:client,fetcher:async u=>new Response(JSON.stringify(u.includes('/auth/')?{id:'user1'}:u.includes('mow_crew_members')?[{company_id:'company1',role:'owner'}]:[]))});const r=await call(h,'/api/billing/connect/onboarding',{method:'POST',headers:{Origin:origin,Authorization:'Bearer fake'},body:'{}'});assert.equal(r.status,503);assert.equal(made,false)});
