import Stripe from 'stripe';
import {randomUUID,randomBytes} from 'node:crypto';
export const FEE_BPS=Object.freeze({starter:350,growth:250,scale:150});
export function feePlan(a){return a?.paid&&a.status==='active'&&FEE_BPS[a.plan]?a.plan:'starter'}
export function feeCents(amount,plan){if(!Number.isSafeInteger(amount)||amount<=0)throw Error('Invalid payment amount');return Math.round(amount*(FEE_BPS[plan]||350)/10000)}
export const PLANS=Object.freeze({growth:{name:'Growth Route',amount:4900,fee_bps:250,price:'price_1UNdfL1fvEozmSlD0Fw44ack'},scale:{name:'Scale & Crew',amount:12900,fee_bps:150,price:'price_1UNdfT1fvEozmSlDxgXTn2gc'}});
const BASE='https://pzymmsfjgspvzbivzvkx.supabase.co',ACCOUNT='acct_1UNcR11fvEozmSlD';
const pub='sb_publishable_KQGD-vWlAlJi_Bv7fSaEvA_YLJpIgyu';
const ORIGINS=new Set(['https://office.mowmatter.com','https://mowmatter-office.onrender.com']);
const EVENTS=new Set(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','customer.subscription.created','customer.subscription.updated','customer.subscription.deleted','invoice.paid','invoice.payment_failed']);
const CONNECT_ACTIVITY=new Set(['charge.refunded','charge.dispute.created','charge.dispute.updated','charge.dispute.closed','payout.paid','payout.failed']);
export function subscriptionState(sub){const item=sub.items?.data?.[0],plan=Object.keys(PLANS).find(k=>PLANS[k].price===item?.price?.id)||'starter';return {plan,status:sub.status,paid:plan!=='starter'&&sub.status==='active'&&sub.latest_invoice?.status==='paid',period_end:item?.current_period_end??sub.current_period_end??null,cancel_at_period_end:!!sub.cancel_at_period_end};}
export async function readRaw(req,max=262144){let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)throw Object.assign(Error('Request too large'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}
export function createBilling({env=process.env,fetcher=fetch,stripeClient}={}){
 const key=env.STRIPE_SECRET_KEY||env.stripe_live_secret_key,dbkey=env.SUPABASE_SECRET_KEY||env.SUPABASE_SERVICE_ROLE_KEY||env.supabase_api_secret_key;
 const connectSigning=env.STRIPE_CONNECT_WEBHOOK_SECRET;
 const connectEnabled=env.STRIPE_CONNECT_ENABLED==='true';
 const signing=env.STRIPE_WEBHOOK_SECRET||env.stripe_webhook_secret;
 const stripe=stripeClient||(key?new Stripe(key,{apiVersion:'2026-08-26.dahlia',maxNetworkRetries:2,timeout:12000}):null);
 let readiness=null,readinessAt=0;
 async function db(path,method='GET',body,prefer){if(!dbkey)throw Object.assign(Error('Billing database is not configured'),{status:503});const r=await fetcher(BASE+'/rest/v1/'+path,{method,headers:{apikey:dbkey,...(dbkey.startsWith('eyJ')?{Authorization:'Bearer '+dbkey}:{}),'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});if(!r.ok)throw Object.assign(Error('Billing record could not be saved'),{status:503});const raw=await r.text();return raw?JSON.parse(raw):null;}
 async function ready(){if(readiness&&Date.now()-readinessAt<60000)return readiness;let verified=false,databaseVerified=false;try{if(stripe){const account=await stripe.accounts.retrieve();verified=account.id===ACCOUNT&&account.charges_enabled===true;}}catch{}try{if(dbkey){await db('mow_billing_accounts?select=company_id&limit=1');databaseVerified=true;}}catch{}readiness={checkout_enabled:verified&&databaseVerified&&connectEnabled&&!!signing,stripe_account_verified:verified,database_verified:databaseVerified,stripe_key_configured:!!key,webhook_configured:!!signing,database_key_configured:!!dbkey,plans:Object.entries(PLANS).map(([id,p])=>({id,name:p.name,amount_cents:p.amount,fee_percent:p.fee_bps/100})),connect_onboarding_enabled:verified&&databaseVerified&&connectEnabled,homeowner_payments_enabled:verified&&databaseVerified&&connectEnabled&&!!connectSigning,quoting_addon_enabled:false};readinessAt=Date.now();return readiness;}
 async function owner(req,companyId){const token=req.headers.authorization;if(!token?.startsWith('Bearer '))throw Object.assign(Error('Sign in to Office'),{status:401});const r=await fetcher(BASE+'/auth/v1/user',{headers:{apikey:pub,Authorization:token},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Object.assign(Error('Sign in again'),{status:401});const user=await r.json();const filter=companyId?'&company_id=eq.'+encodeURIComponent(companyId):'';const rows=await db('mow_crew_members?select=company_id,role&user_id=eq.'+encodeURIComponent(user.id)+filter);const member=rows.find(x=>x.role==='owner');if(!member)throw Object.assign(Error('Business owner access required'),{status:403});return {user,cid:member.company_id};}
 async function account(cid){return (await db('mow_billing_accounts?select=*&company_id=eq.'+encodeURIComponent(cid)))[0];}
 async function ensureCustomer(cid){let a=await account(cid);if(a?.customer_id?.startsWith('acct_'))return a;if(a?.customer_id)throw Object.assign(Error('Contact support to migrate your existing billing account'),{status:409});await db('mow_billing_accounts','POST',{company_id:cid},'resolution=ignore-duplicates,return=minimal');const company=(await db('mow_crew_companies?select=name&id=eq.'+encodeURIComponent(cid)))[0];const c=await stripe.v2.core.accounts.create({display_name:company?.name||'Lawn care business',identity:{country:'US'},dashboard:'full',defaults:{currency:'usd',responsibilities:{fees_collector:'stripe',losses_collector:'stripe'}},configuration:{customer:{},merchant:{capabilities:{card_payments:{requested:true}}}},metadata:{mowmatter_company:cid}},{idempotencyKey:'mowmatter-connect-'+cid});await db('mow_billing_accounts?company_id=eq.'+encodeURIComponent(cid),'PATCH',{customer_id:c.id},'return=minimal');return account(cid);}
 async function connected(a){if(!a?.customer_id?.startsWith('acct_'))return null;const c=await stripe.v2.core.accounts.retrieve(a.customer_id,{include:['configuration.merchant','requirements']});return {account_id:c.id,payments_ready:c.configuration?.merchant?.capabilities?.card_payments?.status==='active',payouts_ready:c.configuration?.merchant?.capabilities?.stripe_balance?.payouts?.status==='active',requirements:c.requirements?.summary?.minimum_deadline?.status||'Check Stripe for verification requirements'};}
 async function accounting(a){const c=await connected(a);if(!c)return {connection:null,transactions:[],payouts:[],balances:null};const opts={stripeAccount:c.account_id};const [charges,payouts,balance]=await Promise.all([stripe.charges.list({limit:50,expand:['data.balance_transaction']},opts),stripe.payouts.list({limit:20},opts),stripe.balance.retrieve({},opts)]);return {connection:c,balances:{available:balance.available,pending:balance.pending},transactions:charges.data.map(x=>({id:x.id,date:x.created,amount_cents:x.amount,currency:x.currency,status:x.refunded?'refunded':x.paid?'paid':x.status,refunded_cents:x.amount_refunded,platform_fee_cents:x.application_fee_amount||0,total_fee_cents:typeof x.balance_transaction==='object'?x.balance_transaction?.fee:null,net_cents:typeof x.balance_transaction==='object'?x.balance_transaction?.net:null,description:x.description||'Customer payment'})),payouts:payouts.data.map(x=>({id:x.id,amount_cents:x.amount,currency:x.currency,status:x.status,arrival_date:x.arrival_date}))};}

 async function sync(event){if(!EVENTS.has(event.type))return;const o=event.data.object;let sid=o.object==='subscription'?o.id:o.object==='checkout.session'?o.subscription:o.parent?.subscription_details?.subscription||o.subscription;if(typeof sid==='object')sid=sid?.id;if(!sid)return;const sub=await stripe.subscriptions.retrieve(sid,{expand:['latest_invoice']});const customer=(typeof sub.customer_account==='string'?sub.customer_account:sub.customer_account?.id)||(typeof sub.customer==='string'?sub.customer:sub.customer?.id);const rows=await db('mow_billing_accounts?select=company_id&customer_id=eq.'+encodeURIComponent(customer));if(!rows.length)return;const s=subscriptionState(sub);await db('rpc/mow_billing_apply','POST',{eid:event.id,etype:event.type,ec:event.created,customer,subscription:sub.id,p:s.plan,s:s.status,is_paid:s.paid,pend:s.period_end,cancel_end:s.cancel_at_period_end});}
 return async function handle(req,res){const pathname=new URL(req.url,'http://localhost').pathname;if(!pathname.startsWith('/api/billing'))return false;
 const headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Vary':'Origin'};const send=(status,data)=>{res.writeHead(status,headers);res.end(JSON.stringify(data));};
 try{
  if(pathname==='/api/billing/connect/webhook'){if(req.method!=='POST'){send(405,{error:'POST required'});return true}if(!stripe||!connectSigning||!dbkey){send(503,{error:'Connect webhook is not configured'});return true}let event;try{event=stripe.webhooks.constructEvent(await readRaw(req),req.headers['stripe-signature'],connectSigning)}catch{send(400,{error:'Invalid webhook signature'});return true}if(!event.livemode||!event.account){send(400,{error:'Wrong Stripe environment or missing account'});return true}if(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed'].includes(event.type)){const session=await stripe.checkout.sessions.retrieve(event.data.object.id,{},{stripeAccount:event.account});const accounts=await db('mow_billing_accounts?select=company_id&customer_id=eq.'+encodeURIComponent(event.account));if(accounts[0])await db('rpc/mow_payment_event','POST',{eid:event.id,etype:event.type,ec:event.created,cid:accounts[0].company_id,sid:session.id,state:session.payment_status==='paid'?'paid':event.type==='checkout.session.async_payment_failed'?'failed':'pending'});}else if(CONNECT_ACTIVITY.has(event.type)){
 const accounts=await db('mow_billing_accounts?select=company_id&customer_id=eq.'+encodeURIComponent(event.account));
 if(accounts[0]){const o=event.data.object;await db('mow_payment_activity?on_conflict=event_id','POST',{
 event_id:event.id,company_id:accounts[0].company_id,account_id:event.account,event_type:event.type,
 object_id:o.id,amount_cents:event.type==='charge.refunded'?o.amount_refunded:o.amount,
 currency:o.currency,status:o.status||(event.type==='charge.refunded'?'refunded':'unknown'),event_created:event.created
 },'resolution=ignore-duplicates,return=minimal');}
 }send(200,{received:true});return true;}
  if(pathname==='/api/billing/webhook'){if(req.method!=='POST'){send(405,{error:'POST required'});return true}if(!stripe||!signing||!dbkey){send(503,{error:'Webhook is not configured'});return true}let event;try{event=stripe.webhooks.constructEvent(await readRaw(req),req.headers['stripe-signature'],signing)}catch(e){send(e.status||400,{error:'Invalid webhook signature or payload'});return true}if(event.livemode!==true){send(400,{error:'Wrong Stripe environment'});return true}await sync(event);send(200,{received:true});return true;}
  const origin=req.headers.origin;if(!ORIGINS.has(origin)){send(403,{error:'Origin not allowed'});return true}headers['Access-Control-Allow-Origin']=origin;
  if(req.method==='OPTIONS'){headers['Access-Control-Allow-Headers']='authorization,content-type';headers['Access-Control-Allow-Methods']='GET,POST,OPTIONS';send(204,null);return true}
  if(pathname==='/api/billing/config'&&req.method==='GET'){send(200,await ready());return true}
  if(req.method!=='POST'){send(405,{error:'POST required'});return true}
  let body;try{body=JSON.parse((await readRaw(req,4096)).toString())}catch(e){throw Object.assign(Error('Invalid request'),{status:e.status||400})}
  const {cid}=await owner(req,body.company_id);let a=await account(cid);
  if(pathname==='/api/billing/status'){send(200,{fee_percent:FEE_BPS[feePlan(a)]/100,...(await ready()),subscription:a?{plan:a.plan,status:a.status,paid:a.paid,period_end:a.period_end,cancel_at_period_end:a.cancel_at_period_end}:{plan:'starter',status:'free',paid:false}});return true}
  if(pathname==='/api/billing/accounting'){const r=await ready();const activity=await db('mow_payment_activity?select=event_id,event_type,object_id,amount_cents,currency,status,event_created&company_id=eq.'+encodeURIComponent(cid)+'&order=event_created.desc,event_id.desc&limit=25');send(200,{...r,fee_percent:FEE_BPS[feePlan(a)]/100,plan:feePlan(a),activity,...(stripe&&r.stripe_account_verified?await accounting(a):{connection:null,transactions:[],payouts:[],balances:null})});return true}
  if(pathname==='/api/billing/connect/onboarding'){if(!(await ready()).connect_onboarding_enabled)throw Object.assign(Error('Stripe Connect setup is awaiting activation'),{status:503});a=await ensureCustomer(cid);const link=await stripe.v2.core.accountLinks.create({account:a.customer_id,use_case:{type:'account_onboarding',account_onboarding:{configurations:['merchant','customer'],refresh_url:'https://office.mowmatter.com/billing.html?onboarding=refresh',return_url:'https://office.mowmatter.com/billing.html?onboarding=returned'}}});send(200,{url:link.url});return true}
  if(pathname==='/api/billing/payment-link'){const r=await ready();if(!r.homeowner_payments_enabled)throw Object.assign(Error('Customer payments are awaiting Stripe Connect activation'),{status:503});const c=await connected(a);if(!c?.payments_ready||!c.payouts_ready)throw Object.assign(Error('Finish Stripe verification and bank setup first'),{status:409});const jobs=await db('mow_crew_jobs?select=id,status,price_cents,cancelled_at&company_id=eq.'+encodeURIComponent(cid)+'&id=eq.'+encodeURIComponent(body.job_id));const job=jobs[0];if(!job||job.cancelled_at||job.status!=='completed'||!Number.isSafeInteger(job.price_cents)||job.price_cents<=0)throw Object.assign(Error('Choose a completed, priced visit'),{status:400});const previous=await db('mow_payment_checkouts?select=*&job_id=eq.'+encodeURIComponent(job.id));if(previous[0]?.status==='paid')throw Object.assign(Error('This visit has already been paid'),{status:409});if(previous[0]?.session_id){const old=await stripe.checkout.sessions.retrieve(previous[0].session_id,{},{stripeAccount:c.account_id});if(old.status==='open'){send(200,{url:old.url});return true}if(old.status==='complete')throw Object.assign(Error('Payment confirmation is pending'),{status:409});}
  const plan=feePlan(a),fee=feeCents(job.price_cents,plan),nonce=randomUUID();const claimed=await db('rpc/mow_payment_claim','POST',{jid:job.id,cid,token:nonce,amount:job.price_cents,bps:FEE_BPS[plan],fee});if(!claimed)throw Object.assign(Error('A payment link is already being prepared'),{status:409});const suffix=[...randomBytes(8)].map(n=>String.fromCharCode(97+n%26)).join('');const session=await stripe.checkout.sessions.create({mode:'payment',line_items:[{price_data:{currency:'usd',unit_amount:job.price_cents,product_data:{name:'Completed lawn care visit'}},quantity:1}],payment_intent_data:{application_fee_amount:fee,metadata:{mowmatter_job:job.id,fee_bps:String(FEE_BPS[plan]),fee_plan:plan}},metadata:{mowmatter_job:job.id},integration_identifier:'mowmatter_homeowner_'+suffix,expires_at:Math.floor(Date.now()/1000)+1800,success_url:'https://mowmatter.com/payment.html?result=returned',cancel_url:'https://mowmatter.com/payment.html?result=cancelled'},{stripeAccount:c.account_id,idempotencyKey:'mowmatter-job-'+nonce});await db('mow_payment_checkouts?job_id=eq.'+encodeURIComponent(job.id)+'&nonce=eq.'+nonce,'PATCH',{session_id:session.id},'return=minimal');send(200,{url:session.url});return true;}
  if(!(await ready()).checkout_enabled)throw Object.assign(Error('Billing setup is being completed. No payment was taken.'),{status:503});
  if(pathname==='/api/billing/portal'){if(!a?.customer_id)throw Object.assign(Error('No subscription to manage yet'),{status:400});const p=await stripe.billingPortal.sessions.create({customer_account:a.customer_id,configuration:'bpc_1UNdtv1fvEozmSlD6FhdOwa1',return_url:'https://office.mowmatter.com/billing.html'});send(200,{url:p.url});return true}
  if(pathname!=='/api/billing/checkout'){send(404,{error:'Not found'});return true}
  if(!PLANS[body.plan])throw Object.assign(Error('Choose a valid plan'),{status:400});
  a=await ensureCustomer(cid);const subscriptions=await stripe.subscriptions.list({customer_account:a.customer_id,status:'all',limit:100});if(subscriptions.data.some(s=>!['canceled','incomplete_expired'].includes(s.status)))throw Object.assign(Error('You already have a subscription. Use Manage billing.'),{status:409});
  const nonce=randomUUID(),claimed=await db('rpc/mow_billing_checkout_claim','POST',{cid,nonce});
  if(!claimed){a=await account(cid);if(a.checkout_session){const existing=await stripe.checkout.sessions.retrieve(a.checkout_session);if(existing.status==='open'&&existing.url){send(200,{url:existing.url});return true}}throw Object.assign(Error('Checkout is already being prepared. Try again shortly.'),{status:409});}
  try{const suffix=[...randomBytes(8)].map(n=>String.fromCharCode(97+n%26)).join('');const session=await stripe.checkout.sessions.create({mode:'subscription',customer_account:a.customer_id,line_items:[{price:PLANS[body.plan].price,quantity:1}],expires_at:Math.floor(Date.now()/1000)+1800,integration_identifier:'mowmatter_office_'+suffix,success_url:'https://office.mowmatter.com/billing.html?checkout=returned',cancel_url:'https://office.mowmatter.com/billing.html?checkout=cancelled'},{idempotencyKey:'mowmatter-checkout-'+nonce});await db('mow_billing_accounts?company_id=eq.'+encodeURIComponent(cid)+'&checkout_nonce=eq.'+nonce,'PATCH',{checkout_session:session.id},'return=minimal');send(200,{url:session.url});}
  catch(e){/* Keep the lease after an uncertain network result to prevent duplicate sessions. */throw e;}
 }catch(e){send(e.status||503,{error:e.status?e.message:'Billing is temporarily unavailable. No new payment was submitted by this request.'});}return true;};
}
