// Shared website brand for account and homeowner emails. Opaque PNG keeps the
// stacked wordmark intact when email clients recolor text in dark mode.
export function emailShell(content, footer = 'The chemistry of curb appeal.') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}a{word-break:break-word}@media(max-width:480px){.pad{padding:24px!important}.title{font-size:28px!important}.brand-image{width:220px!important;height:auto!important}}@media(prefers-color-scheme:dark){.outer{background:#031910!important}.surface{background:#06251b!important;color:#f7f9f3!important}.copy,.title{color:#f7f9f3!important;-webkit-text-fill-color:#f7f9f3!important}.muted{color:#c4d8ca!important;-webkit-text-fill-color:#c4d8ca!important}.link{color:#c4f500!important;-webkit-text-fill-color:#c4f500!important}.detail{background:#123c2d!important;color:#f7f9f3!important}}[data-ogsc] .surface{background:#06251b!important;color:#f7f9f3!important}[data-ogsc] .copy,[data-ogsc] .title{color:#f7f9f3!important}[data-ogsc] .muted{color:#c4d8ca!important}[data-ogsc] .link{color:#c4f500!important}</style></head><body class="outer" style="margin:0;background:#f7f9f3;font-family:Arial,Helvetica,sans-serif;color:#06251b"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px"><table class="surface" role="presentation" width="560" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;background:#ffffff;color:#06251b;border-radius:16px;overflow:hidden"><tr><td class="pad" bgcolor="#06251b" style="padding:28px 32px;background:#06251b;background-image:linear-gradient(#06251b,#06251b)"><a href="https://mowmatter.com" style="text-decoration:none"><img class="brand-image" src="https://crew.mowmatter.com/email-brand-v2.png" width="220" height="72" alt="MOW MATTER" style="display:block;border:0;width:220px;max-width:100%;height:auto"></a><p style="margin:16px 0 0;font-size:11px;line-height:1.5;font-weight:700;letter-spacing:1.2px;color:#c4f500!important;-webkit-text-fill-color:#c4f500">THE CHEMISTRY OF CURB APPEAL.</p></td></tr><tr><td class="pad" style="padding:32px">${content}</td></tr><tr><td class="pad muted" style="padding:22px 32px;border-top:1px solid #dce5de;font-size:12px;line-height:1.6;color:#527063">${footer}<br><a class="link" href="https://mowmatter.com" style="color:#06251b;text-decoration:underline">mowmatter.com</a></td></tr></table></td></tr></table></body></html>`;
}

export function emailButton(url, label) {
  return `<table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#c4f500" style="background:#c4f500;background-image:linear-gradient(#c4f500,#c4f500);border-radius:8px"><a href="${url}" style="display:inline-block;padding:16px 24px;font-size:16px;line-height:1.4;font-weight:700;color:#06251b!important;-webkit-text-fill-color:#06251b!important;text-decoration:none">${label}</a></td></tr></table>`;
}
