const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const wait=()=>new Promise(r=>setTimeout(r,20));
async function page(scanResult){const dom=new JSDOM(fs.readFileSync(__dirname+'/dist/growth.html','utf8'),{url:'https://office.mowmatter.com/growth.html',runScripts:'outside-only'}),w=dom.window,calls=[];w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.AbortSignal.timeout=()=>undefined;w.MM={ensureSession:async()=>{},session:{access_token:'test'}};w.fetch=async(url,o)=>{const b=JSON.parse(o.body);calls.push(b);return {ok:true,json:async()=>b.action==='profile'?{business_zip:'32164',profile:null}:scanResult}};w.eval(fs.readFileSync(__dirname+'/dist/growth-live.js','utf8'));await w.showMowGrowth('company');return {dom,w,calls};}
function submit(w){w.document.querySelector('#demand-form').dispatchEvent(new w.Event('submit',{cancelable:true}));}
(async()=>{let p=await page({count:7,package_count:7,package_amount_cents:3500,unlocked:false,unlocked_count:0,access_reason:'locked',leads:[],offset:0,onboarding_complete:false,zip:'32164',radius:15});let d=p.w.document;assert.equal(d.querySelector('#demand-zip').value,'32164');assert.deepEqual([...d.querySelector('#demand-radius').options].map(x=>x.value),['15','25']);submit(p.w);await wait();assert.match(d.querySelector('#demand-result').textContent,/There are 7 homeowners/);assert(d.querySelector('#demand-unlock'));assert.equal(d.querySelectorAll('.lead-card').length,0);assert.match(d.querySelector('.lead-disclaimer').textContent,/Mow Matter does not guarantee conversion, booking, or individual project retention/);d.querySelector('#demand-unlock').click();assert(d.querySelector('#lead-register'));assert.match(d.querySelector('#dialog-content').textContent,/\$35/);assert.match(d.querySelector('#dialog-content').textContent,/Already unlocked leads are excluded/);d.querySelector('#demand-zip').value='90210';d.querySelector('#demand-zip').dispatchEvent(new p.w.Event('input'));assert(!d.querySelector('#demand-unlock'));p.w.close();
p=await page({count:1,unlocked:true,unlocked_count:1,access_reason:'subscription',leads:[{first_name:'<script>unsafe</script>',address:'42 Palm Way',city:'Palm Coast',state:'FL',zip:'32164',email:'home@example.invalid',services:['mowing'],frequency:'weekly',distance_miles:2,created_at:'2026-10-07T10:00:00Z'}],offset:0,zip:'32164',radius:15});submit(p.w);await wait();d=p.w.document;assert(!d.querySelector('#demand-unlock'));assert.match(d.querySelector('#demand-result').textContent,/Included free/);assert.equal(d.querySelectorAll('.lead-card').length,1);assert.equal(d.querySelector('.lead-card script'),null);p.w.close();
p=await page({count:0,unlocked:false,unlocked_count:0,leads:[],offset:0,zip:'32164',radius:15});submit(p.w);await wait();assert.match(p.w.document.querySelector('#demand-result').textContent,/No matching/);assert(!p.w.document.querySelector('#demand-unlock'));p.w.close();p=await page({count:0,unlocked:false,unlocked_count:0,leads:[],offset:0,zip:'32164',radius:15});assert(p.w.document.querySelector('#growth-register'));p.w.document.querySelector('#growth-register').click();assert(p.w.document.querySelector('#growth-onboard'));p.w.close();
const a=new JSDOM('<section id="dashboard-leads"></section>',{url:'https://office.mowmatter.com',runScripts:'outside-only'}),w=a.window;w.AbortSignal.timeout=()=>undefined;w.MM={ensureSession:async()=>{},session:{access_token:'test'}};let alerts=0;w.fetch=async(u,o)=>{assert.equal(JSON.parse(o.body).action,'alerts');alerts++;return {ok:true,json:async()=>({count:10,new_count:3,zip:'32164',radius:15})}};w.eval(fs.readFileSync(__dirname+'/dist/growth-live.js','utf8'));await w.showMowLeadAlerts('company');assert.equal(alerts,1);assert.match(w.document.querySelector('#dashboard-leads').textContent,/3 new leads/);assert.equal(w.document.querySelector('a').getAttribute('href'),'growth.html?zip=32164&radius=15');w.close();
console.log('PASS Growth: business ZIP default, radius options, locked details, paid access, disclaimer, stale result clearing, safe lead rendering and empty state');})().catch(e=>{console.error(e);process.exit(1)});
