import {createSetupAI} from './pricing/setup-ai.mjs';
import {createBilling} from './billing/billing.mjs';
import http from 'node:http';
import {pathToFileURL} from 'node:url';
export function extractGeometry(v,depth=0){if(!v||depth>8)return [];if(Array.isArray(v))return v.flatMap(x=>extractGeometry(x,depth+1));if(typeof v!=='object')return [];if(['Polygon','MultiPolygon'].includes(v.type)&&Array.isArray(v.coordinates))return [{type:v.type,coordinates:v.coordinates}];return Object.values(v).flatMap(x=>extractGeometry(x,depth+1));}
export function sanitize(detail,parcel,address){const d=detail.data||detail,i=d.propertyInfo||{},l=d.lotInfo||{},num=v=>v==null||v===''||!Number.isFinite(Number(v))?null:Number(v);return {address:i.address?.label||address,lot_sqft:num(l.lotSquareFeet),latitude:num(i.latitude),longitude:num(i.longitude),parcel_number:l.apn||null,property_use:l.propertyUse||null,geometries:extractGeometry(parcel),mowable_sqft:null,area_status:'needs_confirmation',retrieved_at:new Date().toISOString()};}
export function estimate({mowableSqft,minimumPrice,pricePerThousandSqft,accessAdjustment=0,visitsPerYear=26}){if(![mowableSqft,minimumPrice,pricePerThousandSqft,accessAdjustment,visitsPerYear].every(v=>Number.isFinite(v)&&v>=0)||!mowableSqft||!visitsPerYear)throw Error('Confirm mowable area and valid owner pricing.');const per=Math.round((Math.max(minimumPrice,mowableSqft/1000*pricePerThousandSqft)+accessAdjustment)*100);return {per_visit_cents:per,monthly_average_cents:Math.round(per*visitsPerYear/12),visits_per_year:visitsPerYear,status:'owner_review'};}
const sb='https://pzymmsfjgspvzbivzvkx.supabase.co',publishable='sb_publishable_KQGD-vWlAlJi_Bv7fSaEvA_YLJpIgyu';
const origins=()=>new Set(['https://office.mowmatter.com','https://mowmatter-office.steelfurymx.chatgpt.site','https://mowmatter-office.onrender.com',...(process.env.ALLOWED_ORIGINS||'').split(',').filter(Boolean)]);
export function createServer(){const billing=createBilling(),setupAI=createSetupAI();return http.createServer(async(req,res)=>{res.setHeader('Strict-Transport-Security','max-age=31536000');res.setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'; base-uri 'none'");if(await billing(req,res))return;const origin=req.headers.origin,headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Vary':'Origin'};if(origins().has(origin))headers['Access-Control-Allow-Origin']=origin;const send=(status,value)=>{res.writeHead(status,headers);res.end(JSON.stringify(value));};if(req.url==='/health'&&req.method==='GET')return send(200,{ok:true,property_key_configured:!!(process.env.realestate_api||process.env.REALESTATE_API_KEY)});if(!origins().has(origin))return send(403,{error:'Origin not allowed'});if(req.method==='OPTIONS'){headers['Access-Control-Allow-Headers']='authorization,content-type';headers['Access-Control-Allow-Methods']='POST,OPTIONS';return send(204,null)}if(await setupAI(req,res,send))return;if(req.url!=='/api/property'||req.method!=='POST')return send(404,{error:'Not found'});const auth=req.headers.authorization;if(!auth?.startsWith('Bearer '))return send(401,{error:'Sign in to Office'});const key=process.env.realestate_api||process.env.REALESTATE_API_KEY;if(!key)return send(503,{error:'Property provider is not configured'});
try{let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>5000)return send(413,{error:'Request too large'})}const b=JSON.parse(raw);if(typeof b.address!=='string'||b.address.trim().length<8||b.address.length>250)return send(400,{error:'Enter a complete property address'});if(b.confirm_provider_lookup!==true)return send(400,{error:'Confirm the property lookup before proceeding'});
const permitResponse=await fetch(sb+'/functions/v1/mowmatter-crew',{method:'POST',headers:{apikey:publishable,Authorization:auth,Origin:'https://office.mowmatter.com','Content-Type':'application/json'},body:JSON.stringify({action:'property_access'}),signal:AbortSignal.timeout(15000)}),permit=await permitResponse.json();if(!permitResponse.ok||!permit.company_id||permit.ok!==true)return send(permitResponse.status===401?401:403,{error:permit.error||'Create an owner workspace in Office first'});
const call=async endpoint=>{const r=await fetch('https://api.realestateapi.com'+endpoint,{method:'POST',headers:{'x-api-key':key,'x-user-id':permit.company_id,'Content-Type':'application/json'},body:JSON.stringify({address:b.address.trim()}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status===401||r.status===403?'Property provider rejected the key or endpoint entitlement.':r.status===429?'Property provider usage limit reached.':'Property provider could not return this address.');return r.json()};
const detail=await call('/v2/PropertyDetail');let parcel=null,boundary_error=null;try{parcel=await call('/v1/PropertyParcel')}catch(e){boundary_error=e.message}return send(200,{ok:true,property:sanitize(detail,parcel,b.address.trim()),boundary_error,trial:permit});
}catch(e){send(400,{error:e.name==='TimeoutError'?'Property lookup timed out.':e instanceof SyntaxError?'Invalid request.':e.message||'Property lookup unavailable.'})}})}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)createServer().listen(Number(process.env.PORT)||3000,'0.0.0.0');
